# Generated by Django 6.0.1 on 2026-02-03 00:31

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS pgcrypto;"),
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS postgis;"),
        migrations.RunSQL("CREATE EXTENSION IF NOT EXISTS timescaledb;"),
    ]
