# Generated by Django 6.0.1 on 2026-01-27 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_comment='Movement amount', decimal_places=3, max_digits=10)),
                ('when', models.DateTimeField(auto_now_add=True, db_comment='Movement date and time')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='categories.category')),
            ],
        ),
    ]
