# Generated by Django 6.0.1 on 2026-01-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(db_comment='Category description', db_default='N/A'),
        ),
    ]
