# Generated by Django 6.0.1 on 2026-01-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('INGRESS', 'Ingress type'), ('EGRESS', 'Egress type')], db_default='EGRESS', max_length=7),
        ),
    ]
