# Generated by Django 6.0.1 on 2026-01-27 23:19

import django.contrib.gis.db.models.fields
import telemetry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.UUIDField(db_default=telemetry.models.Uuid(), editable=False, primary_key=True, serialize=False)),
                ('device_id', models.BigIntegerField()),
                ('position', models.JSONField(default=dict)),
                ('payload', models.JSONField(default=dict)),
                ('sensors', models.JSONField(default=dict)),
                ('point_gis', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
