# Generated by Django 6.0.1 on 2026-01-27 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL("""
SELECT create_hypertable(
    'telemetry_telemetry',
    by_range('id', INTERVAL '1 day'),
    migrate_data => TRUE,
    if_not_exists => TRUE
);
        """)
    ]
