# Generated by Django 6.0.1 on 2026-01-28 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_auto_20260127_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telemetry',
            name='sensors',
        ),
    ]
