# Generated by Django 6.0.1 on 2026-01-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0003_remove_telemetry_sensors'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetry',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
