# Generated by Django 6.0.1 on 2026-01-28 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_telemetry_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telemetry',
            options={'managed': False},
        ),
    ]
