# Generated by Django 6.0.1 on 2026-01-28 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_alter_telemetry_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='telemetry',
            table='telemetry',
        ),
    ]
