# Generated by Django 6.0.1 on 2026-02-03 00:26

import luiggi.utils.uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_default=luiggi.utils.uuid.Uuid(), editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('encrypted_password', models.CharField(max_length=255)),
                ('api_token', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['username'], name='auth_user_username_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('username',), name='auth_user_username_uniq'), models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('api_token',), name='auth_user_api_token_uniq')],
            },
        ),
    ]
