# Generated by Django 6.0.1 on 2026-02-03 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0002_auto_20260203_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_logged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
